export const hxbTheme = {
  bg: '#F3F5F7',
  surface: '#FFFFFF',
  text: '#1C1C1E',
  textSecondary: '#8E8E93',
  textTertiary: '#AEAEB2',
  primary: '#00B7FF',
  primaryDeep: '#2F7BFF',
  primarySoft: '#E8F7FF',
  tabUnderline: '#00C2FF',
  tagBlue: '#5AC8FF',
  danger: '#FF3B30',
  orange: '#FF8A3D',
  green: '#3DDB7A',
  greenDeep: '#2BCB6E',
  cyan: '#4DD0F0',
  membershipBg: '#E9D7A8',
  membershipText: '#8A6A2F',
  heroStart: '#2E78FF',
  heroMid: '#3F9BFF',
  heroEnd: '#6FCDFF',
  bannerStart: '#2F86FF',
  bannerEnd: '#4EB6FF',
  assessStart: '#EAF7FF',
  assessEnd: '#D7F0FF',
  cardRadius: 16,
  shadow: {
    shadowColor: '#8E8E93',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
} as const;
