/** Community visual tokens — aligned with Flutter `CommunityTheme` (iOS). */
export const communityTheme = {
  accent: '#007AFF',
  background: '#F2F2F7',
  surface: '#FFFFFF',
  fillSecondary: '#E9E9EB',
  labelPrimary: '#000000',
  labelSecondary: 'rgba(60, 60, 67, 0.60)',
  labelTertiary: 'rgba(60, 60, 67, 0.30)',
  separator: '#C6C6C8',
  likeRed: '#FF3B30',
  radiusMd: 12,
  contentMaxWidth: 720,

  cardBackground: '#FFFFFF',
  cardMarginBottom: 12,
  cardPaddingTop: 14,
  cardPaddingBottom: 14,
  cardPaddingLeft: 16,
  cardPaddingRight: 12,
  avatarSize: 44,
  avatarGap: 12,
  nicknameFontSize: 17,
  metaFontSize: 13,
  metaColor: 'rgba(60, 60, 67, 0.60)',
  bodyFontSize: 15,
  bodyLineHeight: 1.45,
  linkColor: '#007AFF',
  expandFontSize: 15,
  sectionGap: 10,
  imageRadiusSingle: 12,
  imageRadiusGrid: 4,
  imageGap: 4,
  singleImageMaxWidthRatio: 0.62,
  singleImageMaxHeight: 240,
  likeBarPaddingTop: 12,
  actionIconSize: 20,
  actionLabelFontSize: 13,
  actionColor: 'rgba(60, 60, 67, 0.60)',
  likeActiveColor: '#FF3B30',
  actionGap: 24,
  commentPreviewMarginTop: 8,
  commentPreviewPadding: 10,
  commentPreviewRadius: 4,
  commentPreviewBg: 'rgba(0,0,0,0.04)',
  commentLineFontSize: 14,
  commentLineHeight: 1.35,
  sheetTopRadius: 14,
  sheetHandleWidth: 36,
  sheetHandleHeight: 4,
  sheetHandleColor: '#E0E0E0',
  sheetHandleRadius: 2,
  sheetTitleFontSize: 16,
  inputBorderRadius: 20,
  skeletonSeparator: 12,
  skeletonCount: 3,
  emptyIconSize: 56,
  emptyIconColor: 'rgba(60, 60, 67, 0.30)',
  emptyTextColor: 'rgba(60, 60, 67, 0.60)',
  errorIconColor: 'rgba(60, 60, 67, 0.30)',
  videoPlayOverlay: 'rgba(0,0,0,0.38)',
  videoPlayIconSize: 36,
  publishPlaceholderIconSize: 64,
  publishPlaceholderIconColor: 'rgba(60, 60, 67, 0.30)',
  publishPlaceholderTextColor: 'rgba(60, 60, 67, 0.60)',
  publishPlaceholderHintColor: 'rgba(60, 60, 67, 0.30)',
  screenBackground: '#F2F2F7',
  dividerColor: '#C6C6C8',
} as const;

export const communityTypography = {
  largeTitle: {
    fontSize: 32,
    fontWeight: '700' as const,
    color: communityTheme.labelPrimary,
    lineHeight: 37,
    letterSpacing: -0.5,
  },
  headline: {
    fontSize: 17,
    fontWeight: '600' as const,
    color: communityTheme.labelPrimary,
    lineHeight: 21,
  },
  nickname: {
    fontSize: communityTheme.nicknameFontSize,
    fontWeight: '600' as const,
    color: communityTheme.labelPrimary,
    lineHeight: 21,
  },
  meta: {
    fontSize: communityTheme.metaFontSize,
    color: communityTheme.metaColor,
    lineHeight: 18,
  },
  body: {
    fontSize: communityTheme.bodyFontSize,
    lineHeight: communityTheme.bodyFontSize * communityTheme.bodyLineHeight,
    color: communityTheme.labelPrimary,
  },
  caption: {
    fontSize: 13,
    color: communityTheme.labelSecondary,
    lineHeight: 18,
  },
  expand: {
    fontSize: communityTheme.expandFontSize,
    color: communityTheme.accent,
  },
  actionLabel: {
    fontSize: communityTheme.actionLabelFontSize,
  },
  commentLine: {
    fontSize: communityTheme.commentLineFontSize,
    lineHeight:
      communityTheme.commentLineFontSize * communityTheme.commentLineHeight,
    color: communityTheme.labelPrimary,
  },
  commentPrefix: {
    fontSize: communityTheme.commentLineFontSize,
    lineHeight:
      communityTheme.commentLineFontSize * communityTheme.commentLineHeight,
    color: communityTheme.linkColor,
    fontWeight: '600' as const,
  },
  sheetTitle: {
    fontSize: communityTheme.sheetTitleFontSize,
    fontWeight: '600' as const,
    color: communityTheme.labelPrimary,
  },
};
