import {colors, typography} from '@ui/design-system';

export const communityTheme = {
  cardBackground: colors.background,
  cardMarginBottom: 8,
  cardPaddingTop: 14,
  cardPaddingBottom: 14,
  cardPaddingLeft: 16,
  cardPaddingRight: 12,
  avatarSize: 44,
  avatarGap: 10,
  nicknameFontSize: 16,
  metaFontSize: 12,
  metaColor: '#757575',
  bodyFontSize: 16,
  bodyLineHeight: 1.45,
  linkColor: '#576B95',
  expandFontSize: 14,
  sectionGap: 10,
  imageRadiusSingle: 6,
  imageRadiusGrid: 4,
  imageGap: 4,
  singleImageMaxWidthRatio: 0.62,
  singleImageMaxHeight: 240,
  likeBarPaddingTop: 10,
  actionIconSize: 20,
  actionLabelFontSize: 13,
  actionColor: 'rgba(0,0,0,0.65)',
  likeActiveColor: '#F44336',
  actionGap: 24,
  commentPreviewMarginTop: 8,
  commentPreviewPadding: 10,
  commentPreviewRadius: 4,
  commentPreviewBg: 'rgba(0,0,0,0.04)',
  commentLineFontSize: 14,
  commentLineHeight: 1.35,
  sheetTopRadius: 12,
  sheetHandleWidth: 36,
  sheetHandleHeight: 4,
  sheetHandleColor: '#E0E0E0',
  sheetHandleRadius: 2,
  sheetTitleFontSize: 16,
  inputBorderRadius: 20,
  skeletonSeparator: 8,
  skeletonCount: 4,
  emptyIconSize: 56,
  emptyIconColor: '#BDBDBD',
  emptyTextColor: '#757575',
  errorIconColor: '#9E9E9E',
  videoPlayOverlay: 'rgba(0,0,0,0.38)',
  videoPlayIconSize: 36,
  publishPlaceholderIconSize: 64,
  publishPlaceholderIconColor: '#BDBDBD',
  publishPlaceholderTextColor: '#757575',
  publishPlaceholderHintColor: '#9E9E9E',
  screenBackground: '#F5F5F5',
  dividerColor: colors.border,
} as const;

export const communityTypography = {
  nickname: {
    ...typography.subtitle,
    fontSize: communityTheme.nicknameFontSize,
    fontWeight: '600' as const,
  },
  meta: {
    ...typography.caption,
    fontSize: communityTheme.metaFontSize,
    color: communityTheme.metaColor,
  },
  body: {
    fontSize: communityTheme.bodyFontSize,
    lineHeight: communityTheme.bodyFontSize * communityTheme.bodyLineHeight,
    color: colors.text,
  },
  expand: {
    fontSize: communityTheme.expandFontSize,
    color: colors.primary,
  },
  actionLabel: {
    fontSize: communityTheme.actionLabelFontSize,
  },
  commentLine: {
    fontSize: communityTheme.commentLineFontSize,
    lineHeight:
      communityTheme.commentLineFontSize * communityTheme.commentLineHeight,
    color: colors.text,
  },
  commentPrefix: {
    fontSize: communityTheme.commentLineFontSize,
    lineHeight:
      communityTheme.commentLineFontSize * communityTheme.commentLineHeight,
    color: communityTheme.linkColor,
    fontWeight: '600' as const,
  },
  sheetTitle: {
    fontSize: communityTheme.sheetTitleFontSize,
    fontWeight: '600' as const,
    color: colors.text,
  },
};
