module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        root: ['./'],
        alias: {
          // Exact-match (^...$) aliases point at index.* so Metro never
          // require()'s a bare directory (can be undefined under circular
          // init + inlineRequires → "Cannot read property 'X' of undefined").
          // Subpath aliases keep deep imports like @core/webview/platform.
          '^@commons/toolkit$': './packages/commons/toolkit/src/index.ts',
          '^@commons/toolkit/(.+)$': './packages/commons/toolkit/src/\\1',
          '^@core/domain$': './packages/core/domain/src/index.ts',
          '^@core/domain/(.+)$': './packages/core/domain/src/\\1',
          '^@core/navigation$': './packages/core/navigation/src/index.ts',
          '^@core/navigation/(.+)$': './packages/core/navigation/src/\\1',
          '^@core/api-client$': './packages/core/api-client/src/index.ts',
          '^@core/api-client/(.+)$': './packages/core/api-client/src/\\1',
          '^@core/storage$': './packages/core/storage/src/index.ts',
          '^@core/storage/(.+)$': './packages/core/storage/src/\\1',
          '^@core/config$': './packages/core/config/src/index.ts',
          '^@core/config/(.+)$': './packages/core/config/src/\\1',
          '^@core/supabase$': './packages/core/supabase/src/index.ts',
          '^@core/supabase/(.+)$': './packages/core/supabase/src/\\1',
          '^@core/i18n$': './packages/core/i18n/src/index.ts',
          '^@core/i18n/(.+)$': './packages/core/i18n/src/\\1',
          '^@core/webview$': './packages/core/webview/src/index.ts',
          '^@core/webview/(.+)$': './packages/core/webview/src/\\1',
          '^@core/media-player$': './packages/core/media-player/src/index.ts',
          '^@core/media-player/(.+)$': './packages/core/media-player/src/\\1',
          '^@core/im$': './packages/core/im/src/index.ts',
          '^@core/im/(.+)$': './packages/core/im/src/\\1',
          '^@core/realtime$': './packages/core/realtime/src/index.ts',
          '^@core/realtime/(.+)$': './packages/core/realtime/src/\\1',
          '^@core/linking$': './packages/core/linking/src/index.ts',
          '^@core/linking/(.+)$': './packages/core/linking/src/\\1',
          '^@core/permissions$': './packages/core/permissions/src/index.ts',
          '^@core/permissions/(.+)$': './packages/core/permissions/src/\\1',
          '^@core/media-picker$': './packages/core/media-picker/src/index.ts',
          '^@core/media-picker/(.+)$': './packages/core/media-picker/src/\\1',
          '^@core/bluetooth$': './packages/core/bluetooth/src/index.ts',
          '^@core/bluetooth/(.+)$': './packages/core/bluetooth/src/\\1',
          '^@ui/design-system$': './packages/ui/design-system/src/index.tsx',
          '^@ui/design-system/(.+)$': './packages/ui/design-system/src/\\1',
          '^@features/auth$': './packages/features/auth/src/index.ts',
          '^@features/auth/(.+)$': './packages/features/auth/src/\\1',
          '^@features/home$': './packages/features/home/src/index.ts',
          '^@features/home/(.+)$': './packages/features/home/src/\\1',
          '^@features/chat$': './packages/features/chat/src/index.ts',
          '^@features/chat/(.+)$': './packages/features/chat/src/\\1',
          '^@features/community$': './packages/features/community/src/index.ts',
          '^@features/community/(.+)$': './packages/features/community/src/\\1',
          '^@features/settings$': './packages/features/settings/src/index.ts',
          '^@features/settings/(.+)$': './packages/features/settings/src/\\1',
          '^@features/friend$': './packages/features/friend/src/index.tsx',
          '^@features/friend/(.+)$': './packages/features/friend/src/\\1',
          '^@features/live$': './packages/features/live/src/index.tsx',
          '^@features/live/(.+)$': './packages/features/live/src/\\1',
          '^@features/pay$': './packages/features/pay/src/index.tsx',
          '^@features/pay/(.+)$': './packages/features/pay/src/\\1',
          '^@features/video$': './packages/features/video/src/index.tsx',
          '^@features/video/(.+)$': './packages/features/video/src/\\1',
          '^@features/music$': './packages/features/music/src/index.ts',
          '^@features/music/(.+)$': './packages/features/music/src/\\1',
          '^@features/bfui$': './packages/features/bfui/src/index.ts',
          '^@features/bfui/(.+)$': './packages/features/bfui/src/\\1',
          '^@features/classroom$': './packages/features/classroom/src/index.ts',
          '^@features/classroom/(.+)$': './packages/features/classroom/src/\\1',
          '@app': './src',
          '@app/store': './src/store',
          '@app/store/envSlice': './src/store/envSlice',
          '@app/store/appSlice': './src/store/appSlice',
          '@app/navigation/RootNavigator': './src/navigation/RootNavigator',
          '@app/app/AppProviders': './src/app/AppProviders',
        },
        extensions: ['.ios.js', '.android.js', '.js', '.ts', '.tsx', '.json'],
      },
    ],
  ],
};
