module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        root: ['./'],
        alias: {
          '@commons/toolkit': './packages/commons/toolkit/src',
          '@core/domain': './packages/core/domain/src',
          '@core/navigation': './packages/core/navigation/src',
          '@core/api-client': './packages/core/api-client/src',
          '@core/storage': './packages/core/storage/src',
          '@core/config': './packages/core/config/src',
          '@core/supabase': './packages/core/supabase/src',
          '@core/i18n': './packages/core/i18n/src',
          '@core/webview': './packages/core/webview/src',
          '@core/media-player': './packages/core/media-player/src',
          '@core/im': './packages/core/im/src',
          '@core/realtime': './packages/core/realtime/src',
          '@core/linking': './packages/core/linking/src',
          '@core/permissions': './packages/core/permissions/src',
          '@core/media-picker': './packages/core/media-picker/src',
          '@core/bluetooth': './packages/core/bluetooth/src',
          '@ui/design-system': './packages/ui/design-system/src',
          '@features/auth': './packages/features/auth/src',
          '@features/home': './packages/features/home/src',
          '@features/chat': './packages/features/chat/src',
          '@features/community': './packages/features/community/src',
          '@features/settings': './packages/features/settings/src',
          '@features/friend': './packages/features/friend/src',
          '@features/live': './packages/features/live/src',
          '@features/pay': './packages/features/pay/src',
          '@features/video': './packages/features/video/src',
          '@features/music': './packages/features/music/src',
          '@features/bfui': './packages/features/bfui/src',
          '@app': './src',
          '@app/store': './src/store',
          '@app/store/envSlice': './src/store/envSlice',
          '@app/store/appSlice': './src/store/appSlice',
          '@app/navigation/RootNavigator': './src/navigation/RootNavigator',
          '@app/app/AppProviders': './src/app/AppProviders',
        },
        extensions: ['.ios.js', '.android.js', '.js', '.ts', '.tsx', '.json'],
      },
    ],
    // Must be listed last.
    'react-native-reanimated/plugin',
  ],
};
