export const shortVideoTheme = {
  screenBg: '#F5F6F8',
  gradientTop: '#DCEEF9',
  navBarBg: '#FFFFFF',
  primary: '#1890FF',
  primaryLight: '#91D5FF',
  textPrimary: '#1A1A1A',
  textSecondary: '#757575',
  textMuted: '#9E9E9E',
  divider: '#E8E8E8',
  cardRadius: 12,
  tileRadius: 8,
  badgeRadius: 4,
  pillRadius: 24,
  cardShadowColor: 'rgba(0,0,0,0.06)',
  cardShadowOffsetY: 4,
  cardShadowRadius: 12,
  cardShadowOpacity: 1,
  playScreenBg: '#000000',
  coverPlaceholder: '#2A2A2A',
  uploadingOverlay: 'rgba(255,255,255,0.55)',
  reviewingBadgeBg: 'rgba(0,0,0,0.45)',
  tileGradientEnd: 'rgba(0,0,0,0.8)',
  profileMarginH: 16,
  profileMarginTop: 12,
  profilePadding: 16,
  profileAvatarSize: 48,
  profileNameSize: 18,
  profileStoreSize: 13,
  profileBadgeSize: 11,
  profileStatsValueSize: 20,
  profileStatsLabelSize: 12,
  profileStatsDividerH: 28,
  sectionPaddingH: 16,
  sectionPaddingTop: 16,
  sectionPaddingBottom: 12,
  sectionTitleSize: 16,
  helpLinkSize: 13,
  helpIconSize: 14,
  gridPaddingH: 16,
  gridPaddingBottom: 16,
  gridGap: 8,
  gridColumns: 2,
  tileTitleSize: 12,
  tileMetaSize: 11,
  tilePlayIconSize: 14,
  tileReviewBadgeSize: 11,
  publishIconSize: 28,
  publishIconCircle: 44,
  publishTitleSize: 15,
  publishHintSize: 11,
  publishPadding: 16,
  emptyLottieSize: 180,
  emptyFallbackSize: 140,
  emptyTextSize: 14,
  emptyButtonH: 48,
  emptyButtonTextSize: 16,
  emptyHelpSize: 14,
  loadingSpinnerSize: 16,
  loadingTextSize: 13,
  loadingPaddingV: 20,
  playTitleSize: 15,
  playTitleBottom: 28,
  playTitleRight: 72,
  playTitleLeft: 16,
  playBackTop: 4,
  playBackLeft: 4,
  defaultAvatarUrl: 'https://picsum.photos/seed/short_video_profile/200/200',
} as const;

export const shortVideoTypography = {
  profileName: {
    fontSize: shortVideoTheme.profileNameSize,
    fontWeight: '700' as const,
    color: shortVideoTheme.textPrimary,
  },
  profileStore: {
    fontSize: shortVideoTheme.profileStoreSize,
    color: shortVideoTheme.textSecondary,
  },
  profileBadge: {
    fontSize: shortVideoTheme.profileBadgeSize,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  profileStatValue: {
    fontSize: shortVideoTheme.profileStatsValueSize,
    fontWeight: '700' as const,
    color: shortVideoTheme.textPrimary,
  },
  profileStatLabel: {
    fontSize: shortVideoTheme.profileStatsLabelSize,
    color: shortVideoTheme.textSecondary,
  },
};
