import type {ComponentType} from 'react';
import {
  CourseInfoTemplate,
  DesignCourseTemplate,
  FeedbackTemplate,
  FitnessAppTemplate,
  GlassViewTemplate,
  HelpTemplate,
  HotelBookingTemplate,
  HotelFiltersTemplate,
  IntroAnimationTemplate,
  InviteFriendTemplate,
  MediterraneanDietTemplate,
  MyDiaryTemplate,
  NavigationDrawerTemplate,
  RunningViewTemplate,
  TrainingTemplate,
  WaveViewTemplate,
  WorkoutViewTemplate,
} from './templateScreens';

export const BFUI_TEMPLATE_COMPONENTS: Record<string, ComponentType> = {
  introduction_animation: IntroAnimationTemplate,
  hotel_booking: HotelBookingTemplate,
  hotel_filters: HotelFiltersTemplate,
  fitness_app: FitnessAppTemplate,
  my_diary: MyDiaryTemplate,
  training: TrainingTemplate,
  design_course: DesignCourseTemplate,
  course_info: CourseInfoTemplate,
  help: HelpTemplate,
  feedback: FeedbackTemplate,
  invite_friend: InviteFriendTemplate,
  navigation_drawer: NavigationDrawerTemplate,
  glass_view: GlassViewTemplate,
  wave_view: WaveViewTemplate,
  running_view: RunningViewTemplate,
  workout_view: WorkoutViewTemplate,
  mediterranean_diet: MediterraneanDietTemplate,
};
