export const chatTheme = {
  pageBackground: '#EDEDED',
  panelBackground: '#F7F7F7',
  wechatGreen: '#07C160',
  selfBubble: '#95EC69',
  peerBubble: '#FFFFFF',
  titleBlack: '#1A1A1A',
  inputBorder: '#E0E0E0',
  timeBackground: '#22000000',
  divider: '#E5E5E5',
  textSecondary: '#666666',
  textHint: '#999999',
  unreadRed: '#FF0000',
  previewBlack: '#000000',
  iconMuted: 'rgba(0,0,0,0.54)',
  emojiPanelHeight: 220,
  recallWindowMinutes: 3,
} as const;

export const CHAT_EMOJI_LIST = [
  '😀',
  '😂',
  '🥰',
  '😎',
  '🤔',
  '👍',
  '🙏',
  '🎉',
  '❤️',
  '🔥',
  '👋',
  '😭',
  '🤣',
  '😊',
  '🥳',
  '💪',
] as const;
